### ISSUE TITLE
Disagreement with totals vs official CDC numbers?

### ISSUE THREAD

**Issue by ktaylora** [RamiKrispin/coronavirus-csv#2]
Hey Rami -

Thanks for curating this dataset. I'm seeing some differences between this CSV and the official numbers from the CDC. Maybe I'm misusing your 'type' column and assuming that confirmed cases are independent records?
# CDC numbers as of 3/07 : 164 
# From : https://www.cdc.gov/coronavirus/2019-ncov/cases-in-us.html
```r
t <- read.csv(url("https://github.com/RamiKrispin/coronavirus-csv/raw/master/coronavirus_dataset.csv"))
m_united_states <- t[ t$Country.Region == "US", ]
m_united_states <- m_united_states[ m_united_states$type == "confirmed", ]
# there are negative values in here, but will leave them in and let
# aggregate sort it out
m_united_states<- aggregate(cases~Province.State+date, m_united_states, FUN=sum)
print(sum(m_united_states$cases))
[1] 417
```

**Comment by RamiKrispin** [comment]
Hi @ktaylora,

Please note that I am using [John Hopkins repo](https://github.com/CSSEGISandData/COVID-19) as the source for the CSV file, and therefore the terminology in this repo aligned with the one John Hopkins are using. Here are the definitions for the case type:

* Confirmed: the number of confirmed cases. For Hubei Province: from Feb 13 (GMT +8), we report both clinically diagnosed and lab-confirmed cases. For lab-confirmed cases only (Before Feb 17), please refer to [who_covid_19_situation_reports](https://github.com/CSSEGISandData/COVID-19/tree/master/who_covid_19_situation_reports). For Italy, diagnosis standard might be changed since Feb 27 to "slow the growth of new case numbers." ([Source](https://apnews.com/6c7e40fbec09858a3b4dbd65fe0f14f5))
* Deaths: the number of deaths.
* Recovered: the number of recovered cases.

As for the negative cases, it may relate to either typo error or change in the classification of the case (on the original dataset). I opened the following [issue](https://github.com/CSSEGISandData/COVID-19/issues/285) to clarify on some of those cases.

Hope that makes sense,
Rami

**Comment by ktaylora** [comment]
That helps, Rami. In further digging, it looks like the CDC is more conservative in their testing and validation than individual states (in the US) and some other countries. This makes for more robust data for statistics, but at the expense of being slower and less useful for early detection. Perhaps there's value in leaning on the CDC data for demographic modeling and the John Hopkins data for early change detection.

I'll follow the conversation for the issue you opened to see what the clarifications are. 

Thanks, again -
